# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kavilo < Formula
  desc "A lightweight personal AI assistant — single binary, zero dependencies"
  homepage "https://github.com/rdu16625/kavilo"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.3/kavilo_darwin_amd64.zip"
      sha256 "53eba3eb6c7c39e61bd685201158eb9cb8e478302c0e3768fc0f6168cee89c9d"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.3/kavilo_darwin_arm64.zip"
      sha256 "613c3cb87f28e2dc6b3f8eb598dffb8390cb5f66eac2e995e0cdcd5198855439"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.3/kavilo_linux_amd64.tar.gz"
      sha256 "dfd2e5c0ab8170b3c496b88ed1344f4c3cc48bae603469a374998201f9293fa4"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.3/kavilo_linux_arm64.tar.gz"
      sha256 "9354eebeb47c7dda4c7caf08b99bcb609179be1943f0dbbfbc32c8272c1ee867"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  def caveats
    <<~EOS
      To run kavilo in the background and restart it at login:
        brew services start kavilo

      To stop it:
        brew services stop kavilo

      On macOS, screen capture is usually more reliable when kavilo is launched
      from a GUI terminal app that already has Screen Recording permission.
    EOS
  end

  service do
    run [opt_bin/"kavilo", "start"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/kavilo.log"
    error_log_path var/"log/kavilo.err.log"
  end

  test do
    system "#{bin}/kavilo", "version"
  end
end
