# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kavilo < Formula
  desc "A lightweight personal AI assistant — single binary, zero dependencies"
  homepage "https://github.com/rdu16625/kavilo"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.4/kavilo_darwin_amd64.zip"
      sha256 "bff04aa12ec893e47ba3a0f68117dcf361ae4418d974b21fa837e4f920c8206a"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.4/kavilo_darwin_arm64.zip"
      sha256 "ffb521cafdceab70be68619c6422761db74f40cfa9a63c09309044e66c9c7626"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.4/kavilo_linux_amd64.tar.gz"
      sha256 "4332ce7403d6c74b674760abbcc62236856e99c86fc8def3a727a5d9d9a36d46"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.4/kavilo_linux_arm64.tar.gz"
      sha256 "b730334b1904073fa7b3ba70799701f3c4fc203ec090718977e625064e2fa244"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  def caveats
    <<~EOS
      To run kavilo in the background and restart it at login:
        brew services start kavilo

      To stop it:
        brew services stop kavilo

      On macOS, screen capture is usually more reliable when kavilo is launched
      from a GUI terminal app that already has Screen Recording permission.
    EOS
  end

  service do
    run [opt_bin/"kavilo", "start"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/kavilo.log"
    error_log_path var/"log/kavilo.err.log"
  end

  test do
    system "#{bin}/kavilo", "version"
  end
end
