# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kavilo < Formula
  desc "A lightweight personal AI assistant — single binary, zero dependencies"
  homepage "https://github.com/rdu16625/kavilo"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.2/kavilo_darwin_amd64.zip"
      sha256 "bb86713975c877b2572f5d51dfa1a2c393592ee5a80e6df3cc93f82c9c8232f4"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.2/kavilo_darwin_arm64.zip"
      sha256 "e5baa93483cb9cbbd45ce119507b7915ed732f8d9770dbf59bc9cd01ea94e64d"

      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.2/kavilo_linux_amd64.tar.gz"
      sha256 "dae0ffad0ac3b7577051ee1d9f03fc3167c588d7ae0fb53e8e397fc446592d2c"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdu16625/homebrew-tap/releases/download/v0.2.2/kavilo_linux_arm64.tar.gz"
      sha256 "b686782370965e0b673c6090d71729a8f1f01b508f80198b37a5d42cc9a6e4ab"
      define_method(:install) do
        bin.install "kavilo"
      end
    end
  end

  def caveats
    <<~EOS
      To run kavilo in the background and restart it at login:
        brew services start kavilo

      To stop it:
        brew services stop kavilo

      On macOS, screen capture is usually more reliable when kavilo is launched
      from a GUI terminal app that already has Screen Recording permission.
    EOS
  end

  service do
    run [opt_bin/"kavilo", "start"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/kavilo.log"
    error_log_path var/"log/kavilo.err.log"
  end

  test do
    system "#{bin}/kavilo", "version"
  end
end
